local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 7.5
  publish_frequency: 7.5
  static_map: false
  rolling_window: true
  width: 22.0
  height: 22.0
  resolution: 0.1
